######################
####### CONFIG #######
######################
server:
  port: 8082

######################
##### DATASOURCE #####
######################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: MySql2022!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

######################
###### OPEN API ######
######################
spring-doc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
